# mysql
spring:
    # 环境 dev|test|prod
    profiles:
        active: ${spring.profiles.active}
    # jackson时间格式化
    jackson:
        time-zone: GMT+8
        date-format: yyyy-MM-dd HH:mm:ss
    thymeleaf:
        cache: false
        prefix: classpath:/templates/
        suffix: .html
        encoding: UTF-8
    http:
        #上传文件大小设置
        multipart:
            maxFileSize: 10Mb
            maxRequestSize: 50Mb
#management.endpoints.web.exposure.include=prometheus
#management.server.port=8091
management:
    endpoints:
        web:
            exposure:
                include: health,info,env,prometheus,metrics,httptrace,threaddump,heapdump


logging:
    config: ${spring.profiles.logback}
    
---

spring:
  profiles: local
  
server:
    name: Aham-Biz-Web
    tomcat:
        max-threads: 1000
        min-spare-threads: 30   
    port: 8090
---

spring:
  profiles: dev,test,prod
  
server:
    name: Aham-Biz-Web
    port: 8090
    tomcat:
        max-threads: 1000
        min-spare-threads: 30